# Generated by Django 5.1.3 on 2024-12-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TVM', 'troca de velas de ingição do motor'), ('TOF', 'troca de óleo e filtro'), ('MF', 'verificação e substituição de componentes, como pastilhas, discos e fluido de freio.'), ('AB', 'alinhamento e balanceamento do carro'), ('TP', 'troca de pneus'), ('TCD', 'trocar as correias dentadas e verificar a tensão'), ('RS', 'reparo de suspensão'), ('TB', 'troca da bateria'), ('AC', 'manutenção preventiva, limpeza, substituição de filtros e recarga de gás refrigerante'), ('TSE', 'verificação e troca do sistema de escape'), ('D', 'diagnosticar e verificar problema de acordo com relato do cliente'), ('LSE', 'lavagem e secagem da parte externa (lataria) do carro'), ('HI', 'higienizar parte interna do carro, apirando e limpando painel de controle'), ('CDV', 'cristalização dos vidros'), ('VDP', 'vitrificação da pintura para maior resistência e brilho')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocolo', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_manutencao', models.ManyToManyField(to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
